# Generated by Django 5.0 on 2023-12-19 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fechaNacimientoCiene',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
